### ISSUE TITLE
Project load hangs at "Unpickling" when loding project with non-ASCII chracters.

### ISSUE THREAD

**Issue by lalegion** [jliljebl/flowblade#341]
Hello to everyone! I'm a new user to flowblade but have been producing video for more than 15 years. I find flowblade to be the only true professional oriented video editor on linux. That's why I'm so excited about it.
So far it has been rock solid (Running on Mint 18.1 KDE / Acer v3 772g laptop) but today when I was trying to open a project I saved yesterday, flowblade just lock on loading with a message "Unpickling".
And that's it, have to kill the program... Any ideas???

Flowblade 1.10

Thanks in advance,
Lalegion.

**Comment by dvdlvr** [comment]
This is in the part that loads the project.
There could be something in the file that causes a problem.
If you can attach the flb file that you are trying to open I can try to find out where the problem is. And from that hopefully find a solution.

**Comment by lalegion** [comment]
Ok I think I have discovered something.
The problem seems to be with the name of the project itself. I was using a spanish sentence as a name: "Año nuevo" and apparently the character 'ñ' is somehow not supported. I was able to import all my footage and even save the project but if I tried to open it later it would stuck on "Unpickling..."
I was able to reproduce this effect twice.

Renaming the project with Dolphin and renaming inside the project file with kate (in text mode) can solve the problem.

Thanks and hope it helps!!
It would be very interesting to know if you can reproduce this.

Lalegion.

**Comment by dvdlvr** [comment]
I created a project with the same name "Año nuevo.flb" and was able to open it without problem, several times. I've closed Flowblade and opened it fresh, then opened the project without problems.

Maybe it's linked to Mint, as I'm on Ubuntu 16.10.
Or it could be linked to some environment variable. Perhaps LANG?
This is my setting
$ echo $LANG
en_US.UTF-8

**Comment by lalegion** [comment]
Ok, thanks for your time... I'm confused now...
by the way $ LANG resolves to:
sv_SE.UTF-8

Might be mint...
Lalegion.

**Comment by jliljebl** [comment]
We had an earlier report on similar issue, and I added this line just fix it:

        PROJECT().name = unicode(os.path.basename(filenames[0]), "utf-8")

...but the proglem didn't reproduce then either. @lalegion can you run Flowblade in terminal and post output here?

**Comment by lalegion** [comment]
Wow I'm even more confused now!
I opened terminal and run flowblade (just typed "flowblade")
and the problem disappears... just like that!
but if I opened flowblade the normal way, through the desktop menu, then it happen again "Unpickling..."

this is my konsole when running flowblade:

lalegion@Planet-Legion ~ $ flowblade
FLOWBLADE MOVIE EDITOR 1.10
---------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 6.0.0
OS: Linux Mint 18.1
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
GTK+ version: 3.18.9
User dir: /home/lalegion/.flowblade/
Locale: sv_SE
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
1920 1080
Small height: False
Small width: False
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - flashsv
  - flashsv2                                                                                    
  - flv                                                                                         
  - gif                                                                                         
  - h261                                                                                        
  - h263                                                                                        
  - h263p                                                                                       
  - hap                                                                                         
  - huffyuv                                                                                     
  - jpeg2000                                                                                    
  - jpegls                                                                                      
  - ljpeg                                                                                       
  - mjpeg                                                                                       
  - mpeg1video                                                                                  
  - mpeg2video                                                                                  
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - snow
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libopenjpeg
  - libschroedinger
  - libtheora
  - libvpx
  - libvpx-vp9
  - libwebp
  - libx264
  - libx264rgb
  - libx265
  - libxvid
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - dca
  - eac3
  - flac
  - g723_1
  - mp2
  - mp2fixed
  - nellymoser
  - real_144
  - sonic
  - sonicls
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopencore_amrnb
  - libopus
  - libshine
  - libspeex
  - libtwolame
  - libvo_aacenc
  - libvo_amrwbenc
  - libvorbis
  - libwavpack
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - apng
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - bit
  - caf
  - cavsvideo
  - crc
  - dash
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffm
  - ffmetadata
  - filmstrip
  - flac
  - flv
  - framecrc
  - framemd5
  - g722
  - g723_1
  - gif
  - gxf
  - h261
  - h263
  - h264
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - oga
  - ogg
  - oma
  - opus
  - alaw
  - mulaw
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - rtsp
  - sap
  - segment
  - stream_segment,ssegment
  - singlejpeg
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
  - alsa
  - caca
  - fbdev
  - opengl
  - oss
  - pulse
  - sdl
  - v4l2
  - xv
...
MLT detection succeeded, 152 formats, 84 video codecs and 68 audio codecs found.
463 MLT services found.
Loading render profiles...
Proxy encoding MPEG-4 Preset Ultrafast ...available
Proxy encoding MPEG-2 Transport Stream ...available
Loading filters...
MLT service ladspa.1210 not found.
Brightness dropped, MLT version too low for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Natron not found
Player initialized with profile:  HD 1080p 23.98 fps
Selected color NOT detected
BG color detected
Autosave started...
Save project autosave_16582d9c34c34b09e53275f58b0c4886
Loading año nuevo.flb, SAVEFILE_VERSION: 5
Player initialized with profile:  HD 1080p 23.98 fps
Autosave started...
Save project autosave_16582d9c34c34b09e53275f58b0c4886
Exiting app...
lalegion@Planet-Legion ~ $

**Comment by dvdlvr** [comment]
Ah, that is interesting. I always started it from the command line when I didn't have the problem, but when I open it through the desktop I have the same problem and I get a crash report.

**Comment by lalegion** [comment]
Uff Good to know... I was starting to feel like Cassandra.. ;)))

**Comment by dvdlvr** [comment]
Well, I had to look up what that meant. You're never too old to learn :-)

**Comment by lalegion** [comment]
By the way, the first time I opened it, it did crash because I waited without touching until it finally crashed (had the feeling the program entered a kind of loop because before crashing the computer went unresponsive) after that, I have always interrupt the "unpickling" by closing it. So no crash..

**Comment by jliljebl** [comment]
So works from terminal but not from installed .deb...holy hell this is nasty.

The cause seems relatively clear:
- profile attribute is actually removed from Project instance on save because it is a Swig object that cannot be pickled: persistance.py line 178 (in repository)
- profile attribute is re-recreated on load from project_desc: persistance.py line 358
- the whole thing working relies on *Project.profile* attribute not being used on load before it is created
- Now the BigTCDisplay object (timecode display on middle left) gets updated before load is complete 

...and this only shows on some systems...effin hell.

This will be fixed for next release, there are multiple ways of doing it, we just need tio figure out what is best way to do it, simplest being adding **try: except:** in BigTCDisplay._draw but there may other approaches.

**Comment by jliljebl** [comment]
Ok, I just pushed the quick fix. This still needs more work, because the problem is fundamentally in the design: load has to run in own thread, we have limited control on Gtk requesting draw events, some objects are un-pickleable and have to be destroyed on save and re-created on load.

All this doesn't add up perfectly, but I thought that possible problems would show in development, but apparently not.

**Comment by dvdlvr** [comment]
@Janne: With the quick fix in place I still get the same result: A 'standard' project with only Latin letters will open without a problem, when launched from the dash, but a project with a name containing a special character will not load, as described.

However, I now get a different crash report. Same style, but probably one or two lines further down the line.
![flowblade-crash-2](https://cloud.githubusercontent.com/assets/7942463/23213218/5b3a4700-f90a-11e6-9df0-18c1de2cbb9e.png)

If I open Flowblade, then a normal project I get no crash. If I then open the special name project it will just hang (with the Unpickling msg) and I don't seem to get crash report.
If I open Flowblade, then a special name project I tend to get the crash report.

I'll start putting some debug messages in the code that starts with the Unpickling message to try and pinpoint exactly where it hangs.

**Comment by jliljebl** [comment]
Ok, tell me know what you find out. Both problems are caused by project attributes being accessed before they are re-created on load, project.c_seq is added back to project object at line persistance.py 412.

We should fix all these instance by instance and/or try to find a common cause that can be eliminated.

**Comment by dvdlvr** [comment]
Ok, got it.
The problem is caused by this debug message in persistance.py around line 360
print "Loading " + project.name + ", SAVEFILE_VERSION:", project.SAVEFILE_VERSION

It's the project.name part that causes the problem.
I tried replacing it with unicode(project.name,"utf-8") but then it still hangs.
Just removing the print statement solves the problem.
So, still not sure what the underlying problem is in project.name, but the project is loaded normally and the name is properly displayed after opening, once the print statement is commented out.
![flowblade-no-crash](https://cloud.githubusercontent.com/assets/7942463/23214097/cc0fd6b8-f90d-11e6-9d44-700aa4674045.png)

**Comment by jliljebl** [comment]
I have no clue at all of the cause of this. Well, that print statement has to go, let's just put in something like "Loading project...", but I would like to understand this issue, the project name is in utf already, so maybe converting it utf ->  Python type **str** could somehow make this go away.

**Comment by dvdlvr** [comment]
I tried using str() on it too, but to no avail.
I'm trying to find out what the problem is.
We can print the project profile_desc without a problem at the same point in the program.
I'll have to read up on string types and conversions in python.

**Comment by dvdlvr** [comment]
I still have a problem with github - only 1 valid patch was used for the pull request :-)
I haven't found the underlying reason, but the fix, which is removing the project.name print, should work.

**Comment by jliljebl** [comment]
Well, its not always super easy to stuff I right with git. I haven't done a pull request in a while don't remember clearly, but I think creating a development branch and doing patches in that (instead of master branch), and then doing pull request from that branch is a way to go generally.

**Comment by jliljebl** [comment]
WORKAROUND FOR THIS ISSUE:

1) Start Flowblade in terminal with command:
    flowblade
2) Load the project causing the problem. 
3) Save it with name that has only ASCII characters.

Problem is fixed in 1.14 but I'm leaving this open for now for info purposes.

**Comment by lalegion** [comment]
Hey Thanks a lot to both of you for taking the time to help!
Will stay tuned!

**Comment by jliljebl** [comment]
Fixed in 1.14 closing.
