### ISSUE TITLE
Feature request: Three point edit both ways

### ISSUE THREAD

**Issue by lalegion** [jliljebl/flowblade#342]
I have said before how much I admire this project. I consider it the only professional oriented alternative on linux. It has been clearly inspired (in a perfect way) by Avid.
Been playing around for a couple of weeks because I'm about to start a new project and want to feel confortable with it and I found something missing, which I believe it might be somehow easy to solve.

I have been editing for many years, more than 15 (social events, corporate productions, music videoclips, tv shows) and I have been using the "three point edit" for quite some time and I have noticed that in flowblade it works "one way only".
I can mark IN and OUT point in my timeline and then an IN point in my clip monitor and that works just fine BUT if I want to do the opposite, I mean, mark IN and OUT point on my clip monitor (insert) and only an IN point in my timeline, it doesn't work. It ask me to set two points in my timeline.

Historically "three point edit" works both ways and I think it would be an extra point to flowblade!!!

Thanks!
Lalegion.

**Comment by jliljebl** [comment]
Sure, this can be done. I have to look into the details a bit as I do not want to add another monitor button, but should be easy enough to do for 1.14.

Thanks for the kind words, AVID was definitely one source for the taken  design approach.

**Comment by lalegion** [comment]
Hey, don't mention it. You and the project deserve it.
By the way, "three point edit" does not need an extra button, it would be the same one but working both ways. whether you mark 2 points in the timeline and 1 in the clip or 2 in the clip and 1 in the timeline, you would always have to press the same button. No need to add or remove anything from the layout.
That's the nice thing. Just need to add an extra functionality into the same button.
Let me know if it is not clear enough.

Keep the great work.
Lalegion.

**Comment by jliljebl** [comment]
Fixed in repo, will be in 1.14.

**Comment by lenzwerf** [comment]
I'm sorry but I still can't insert a portion of a source clip, marker by in-out, into the timeline marked only with an in point. The command 'Y' inserts at the next edit or cut. It ignores my in-point. Normally an edit program would see in points as leading.

If 3 point edit really works and there's a way to change the keyboard shortcuts it would be great.

I'm at version 2.2.0-2
