### ISSUE TITLE
Make keyboard shortcuts user configurable

### ISSUE THREAD

**Issue by ahangarha** [jliljebl/flowblade#364]
Hi guys.
Thanks for your great work. I am coming from a FCP and Premiere experience. I want to know if there is anything special about the way you chose shortkeys. It is very confusing for me for example when I want to go to the previous or next cut in timeline. In both FCP and Premiere, the Up Arrow key is for jumping to previous and Down Arrow key for jumping to the next cut. While here, it is exactly opposite.

Is there anything special here?

Isn't it better to follow what is mostly accepted as the norm?

**Comment by ahangarha** [comment]
I have made a branch for replacing UP and Down Arrow functionality Also I have added two more: minus key and equal (plus) key for zoom out and zoom in in timeline.

Should I send pull request or you have some reason for not following this (I assume well accepted) standard in editing software

**Comment by jliljebl** [comment]
So I think there are few view points here:
  * I agree that it is always best to follow established conventions that exist in any category of programs if possible
  * I also believe that breaking existing work flows without providing option to go back to previous behavior is unacceptable unless there are major gains to be had. You can't have "i upgraded to new version and now it works different and I'm pissed" experience forced on users without gaining some massive improvement
  * The probably only way to satisfy both here is to do what the road map says: make possible to configure keyboard shortcuts as user likes
  * I can't accept patch reversing Up and Down arrow, but I will accept adding + and - for timeline  zoom 

The "configurable keyboard shortcuts" is coming to 1.14.If you or anyone is interested in working on it, I can give pointers on how do it. I'll update the title to reflect that this is going to get done someway.

**Comment by ahangarha** [comment]
What about including an option in Preferences > General for Keyboard Shortcuts with two options:
- legacy (Flowblade v<2) as default
- Premiere

and with a notice along with it about the replacement of default Keyboard Shortcuts from version 2

**Comment by dvdlvr** [comment]
@jliljebl - This is something I can work on.

**Comment by jliljebl** [comment]
I can accept a pull request that does this. This kind of added complexity is well contained in existing modules that handle related functionality.

**Comment by ahangarha** [comment]
@dvdlvr If we discuss about how to do, I might be able to take some part in the process

**Comment by dvdlvr** [comment]
@ahangarha Thanks for the offer. Right now I'm still in the process of getting my docs together.
I would need help getting the right key combinations in FCP and Premiere as I don't have these.

My plan is to allow the user to set each key in the preferences window, but also allow Import/Export of key config files.
I have not found any one standard on key config files. I'm thinking about either json or html/xml format. Not sure which is handiest at the moment.

Comments welcome.

**Comment by jliljebl** [comment]
Here is how I see what the approach roughly could be. There are multitude of ways to do this but this is one of the simpler onew.

First we need data create structures for mapping key->action, as these are currently hard coded like this:

    # TAB
    if event.keyval == Gdk.KEY_Tab:
        updater.switch_monitor_display()
        return True

We have to enumerate actions in keyevents.py 

    DELETE_ITEM = 1
    ....
    SWITCH_MONITOR = 19 (or what it happens to be)
    ...etc

...all configurable actions need to be enumerated.

Then we need module global dicts for defaults:

    _keyboard_actions_defaults = {DELETE_ITEM:Gdk.KEY_Delete,
                                    ....
                                   SWITCH_MONITOR:Gdk.KEY_Tab,
                                    ....
                                   }


and:

    _keyboard_actions_premiere_defaults = {DELETE_ITEM:Gdk.KEY_Delete,
                                    ....
                                   SWITCH_MONITOR:Gdk.KEY_Tab,
                                    ....
                                   }

These are mostly same, with the noted differences. Note that stuff "Control + N" for "New" is standard and not handled in keyevents.py and should not be part of this.

Then we need global dict to point to which one is selected:

    _current_keyboard_actions =  _keyboard_actions_defaults

then we can do:

    # TAB
    if event.keyval ==   _current_keyboard_actions[SWITCH_MONITOR]:
        updater.switch_monitor_display()
        return True

and on startup we need to run

    if editorpersistance.prefs.keyboard_actions == DEFAULT_SHORTCUTS:
        _current_keyboard_actions =  _keyboard_actions_defaults
    else:
        _current_keyboard_actions = _keyboard_actions_premiere_defaults

This way user can only select between two defaults sets.

To make every keyaction configurable separately we need to:

- load  _current_keyboard_actions using picle() on startup and save it after user has set new value for keypress
- come up with a GUI component that displays current set key actions aand allows setting it
- **or** save and load  _current_keyboard_actions from some user editable text file to make configuration possible by editing that file, maybe similarly to Render Args stuff
- give reset functionality to go back to defaults.

**Comment by dvdlvr** [comment]
Thanks for the ideas.
I've documented all keys that are used in keyevents.py, so that will be 
my basis.

My idea is to make them totally user configurable. Since we go through 
the process of making these changes we might as well do it all the way.
The easiest to implement would be with separate user readable config 
files. One for each application one would like to emulate. This way 
people can adapt quickly and simply any new layout they wish to use.
Then, at the start of the program, read from preferences which one is to 
be used and load it. In case of any error in the load process, the 
defaults should be used.

I do plan on making a preferences pane where the settings per key can be 
modified and exported as well under a new name.

**Comment by jliljebl** [comment]
Ah yes, you can do it fully from text files, just tested:

    print Gdk.KEY_Home
    >> 65360

and

    print Gdk.keyval_from_name("Home")
    >> 65360

so text files can read:

    MOVE_TO_BEGINNING=Home

so no need to do the Python side dicts.

Integrating handling modifier keys in this scheme may not be easy, didn't test yet.

**Comment by dvdlvr** [comment]
Ah, that's a handy trick. Didn't know that :-)

**Comment by dvdlvr** [comment]
For info:
I found something existing that can save and load accelerator maps in 
python: Gtk.AccelMap
I plan on using that.

Here's a sample of the output file it generates. It has the necessary 
functions to read and interpret it, too, obviously.

; . GtkAccelMap rc-file         -*- scheme -*-
; this file is an automated accelerator map dump
;
; (gtk_accel_path "<flowblade>/Editor/Mark In" "<Shift>i")
; (gtk_accel_path "<flowblade>/Editor/Mark Out" "<Shift><Alt>o")

**Comment by jliljebl** [comment]
Gtk has special classes just for this purpose and Pitivi uses them too, some links:

https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/ShortcutsWindow.html
https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/ShortcutsShortcut.html
https://github.com/GNOME/pitivi/blob/master/pitivi/shortcuts.py
http://www.jakubbrindza.com/2016/06/pitivi-featuring-gtkshortcutswindow.html

I generally avoid these complex APIs and roll something simpler on my own, but if you find these good way of doing this, its all OK.

**Comment by dvdlvr** [comment]
Well, it looks like the AccelMap implementation is broken and/or was 
never fully implemented. I cannot find a decent FULL example and the 
loading of accelmaps using the standard function doesn't work consistently.
I guess this is why all examples I found don't use that mechanism and 
why Pitivi didn't implement that part :-/

I'll go back to something simple.

Using Gtk.Application accelerator / action commands limits us to Gtk 3.0 
and would require a full overhaul of the code. Maybe that's something 
for version 2.0 (or 3.0 or 4.0...) but not for now.

I'll keep you updated.

**Comment by dvdlvr** [comment]
I'm making good progress.
I recoded almost all if Gdk.KEY_xxx entries in keyevents.py to use an action code, as defined in the shortcuts xml file. It looks like this:
    <event code='edit_mode_trim' name='Change Edit Mode to Trim'>3</event>
    <event code='edit_mode_trim' name='Change Edit Mode to Trim'>kp_3</event>
Above you see the 'Trim' edit mode, which is currently linked to the 3 key, is assigned action code 'edit_mode_trim' and in this case I assigned both the standard 3 key as well as the keypad_3 key to the action.

As you can see, you can assign multiple keys to the same action.
For instance, the to_mark_out event is assigned to Alt+o, O and Alt+O as follows:
    <event code='to_mark_out' name='Go To Mark Out' modifiers='ALT'>o</event>
    <event code='to_mark_out' name='Go To Mark Out' modifiers='SHIFT'>o</event>
    <event code='to_mark_out' name='Go To Mark Out' modifiers='ALT+SHIFT'>o</event>

The code:
        if event.keyval == Gdk.KEY_o:
            if (event.get_state() & Gdk.ModifierType.MOD1_MASK):
                monitorevent.to_mark_out_pressed()
                return True
            monitorevent.mark_out_pressed()
            return True
        if event.keyval == Gdk.KEY_O:
            if (event.get_state() & Gdk.ModifierType.MOD1_MASK):
                monitorevent.to_mark_out_pressed()
                return True
            monitorevent.to_mark_out_pressed()
            return True
is now just
        action = _get_shortcut_action(event)
        ....
        if action == 'mark_out':
            monitorevent.mark_out_pressed()
            return True
        elif action == 'to_mark_out':
            monitorevent.to_mark_out_pressed()
            return True

This whole process seems to work fine. Now I need to integrate choosing the layout file to the preferences.
And I still need to create the hardcoded 'defaults' construct to fall back to the current layout.

Then I may try to integrate a manual selection of all the shortcut keys on the preferences dialog and allow the user to save them to a file. That's a lot of learning for me, though :-)

**Comment by jliljebl** [comment]
Great, seems workable. The GTK API s are often unfinished and rolling
something simpler is probably the way to go.

17.4.2017 6.06 ip. "dvdlvr" <notifications@github.com> kirjoitti:

**Comment by ptrg** [comment]
In my opinion the pair of = (equal) and - (minus) characters are bad by design for zoom in and out:
1. In other softwares + and - keys are used for zooming in/out (sometimes combined with Ctrl or Shift), but users are assuming + and - for zooming.
2. The above keys/characters is not in the same place on every keyboard compared to English layout. 
Sometimes they can be typed with a combination of keys. For example on Hungarian keyboards = is Shift+7 and - lays beside the right shift key.

So I suggest NumPad/KeyPad + and - keys for zooming (instead of = and - characters):
Gdk.KEY_KP_Add (0xffab)
Gdk.KEY_KP_Subtract (0xffad)

The full list of Gdk key symbols and values can be found in https://git.gnome.org/browse/gtk+/plain/gdk/gdkkeysyms.h too

**Comment by ahangarha** [comment]
@ptrg Since the big compaies behind Adobe Premiere and FCP use = and - keys for this purpose, I‌ think the wise approach is to follow the same and see what is the widely accepted norm for the exeptions your mentioned?

**Comment by ptrg** [comment]
The problem is not the physical keyboard key beside the BackSpace but the = character itself.
Who thinks about the = to be a key to do a zoom in? Adobe and FPC projects was started/designed in the time when localization of such softwares were not taken in mind (and these softwares are based hardly on the English keyboard's layout). If Adobe and FCP really use the = character (and not the physical key) then they (the developers) still don't care about that the users may work in a localized environments where (as I said) the characters are on different keyboard keys and sometimes they can be produced by very different key combinations only.

If you look at an English keyboard you can see that + and = is on the same physical key that produces the same scan code but the OS gives you a different character depending on the active modifier keys. So the user is seeing that the keyboard key is related to + sign.

Blender (3d suite for modelling, animation, rendering, post-production) uses + and -
GIMP (free and advanced graphics editor) uses + and - 
SMPLayer use w and e but the menu shortcut is + and - 
Firefox (browser) uses + and - with Ctrl modifier
...and a lot of other image and video manipulator, and other softwares in various categories.

Flowblade if written for a free environment where Adobe and FCP is not available, but the above (and other) free softwares are using + and - keys/characters for zooming.

++ If some templates will be available (as you mentioned above) it can be a good solution. For example an additional "General" template where the generally (in any kind of software) used keys are defined for the actions.
Ctrl+C and Ctrl+V (Copy/Paste) is the best example for the widely used  shortcut commands.

**Comment by ahangarha** [comment]
User configurable key binding can help. But as a person has experience on
video editing, I have found the FCP/Primiere key binding really the most
handy one.
I will try to find out how these programs deal with localizations.

**Comment by dvdlvr** [comment]
All, there is a development in testing and further development that will allow this. A bit of patience, please.


Sent from Samsung tablet

-------- Original message --------

**Comment by jliljebl** [comment]
There clearly are two sides to issue and the user configuration is improving, so we wont change defaults at least before user can return to previous behavior.

I'm currently leaning keeping the old behavior default. In next release it will be possible to select the Premiere behavior using GUI.

**Comment by jliljebl** [comment]
@ahangarha @ptrg @dvdlvr I pushed a patch that added "Premiere" keyboard defaults. User can now select between "Flowblade Defaults" and "Premiere" shortcuts. I returned to origin shortcuts for "Flowblade Defaults".

#### Flowblade Defaults

Key | Action
------------ | -------------
**Up Arrow**    |         next cut
**Down Arrow**   |     prev cut
**+**         |          zoom in 
**-**          |               zoom out



#### Premiere

Key | Action
------------ | -------------
**Up Arrow**       |         prev cut
**Down Arrow**    |     next cut
**=**                   |     zoom in 
**-**                      |     zoom out

Others are same. There is still more to do here, but this is what we have now. If you want additional changes for "Premiere" comment here or do a pull request.

**Comment by ahangarha** [comment]
Great job
Thanks

**Comment by Shamaoke** [comment]
Despite the fact that the hotkey settings graphical interface is still missing, you can configure the keys by editing an `*.xml` file at `/usr/share/pyshared/Flowblade/res/shortcuts`.

I have questions regarding the keys configuration.

1. Is there a user accessed directory where you can place a configuration file?

2. Where can I get the full list of keyboard keys aliases I can use at the configuration file?

3. Is there any way to set the mouse keys/wheel as a hotkey?

Thanks.

**Comment by jliljebl** [comment]
> Is there a user accessed directory where you can place a configuration file?

No, there isn't currently. You can edit/add new the file in the folder you mentioned to get your own configuration. We really would like to offer GUI for doing this but just haven't got around to doing this yet, there has always been other more pressing features/bugs.

> Where can I get the full list of keyboard keys aliases I can use at the configuration file?

We have the line below in our key handling code:

    key_name = Gdk.keyval_name(event.keyval).lower()

so to get value to put in configuration file you have to get it from here https://lazka.github.io/pgi-docs/Gdk-3.0/constants.html and use the lower case version key name after part Gdk.KEY_

So in this list there is constant *Gdk.KEY_KP_2* for keypad number 2. Our configuration file uses name *kp_2* for this key.

    Is there any way to set the mouse keys/wheel as a hotkey?

No, those are hard coded in application code.

**Comment by Shamaoke** [comment]
@jliljebl Thanks. This is useful information.

Also, it should be noted, that before setting a hotkey in an `*.xml` shortcuts scheme file, it firstly should be declared in the `_set_key_names` method, which is located in the `/usr/share/pyshared/Flowblade/shortcuts.py` file. For example.

```python
def _set_key_names():
    global _key_names, _mod_names
    # Start with an empty slate
    _key_names = {}

    _key_names['a'] = "A"
    _key_names['b'] = "B"
    _key_names['c'] = "C"
   # etc...
```
If you don't declare a key, which you going to use in your scheme file, then after changing a shortcuts scheme, it will be impossible to change it back, since the keyboard shortcuts dialog (_Edit_ → _Keyboard Shortcuts_) will stop to appear when calling.

Despite that, your keys still will be working.

**Comment by lenzwerf** [comment]
Thank you all for the efford.

I've been struggling with editing the settings but I'll probably get it done with the info provided here but...
I would like to emphatize the importance of making shortcut keys configureable. I've worked as an editor and a kind of system manager for a postproduction company and I learned that all pro editors have their own keyboard settings. The first thing they do is change the setting to their workflow. Some editors learned on an Adobe or Final cut system, others use the Avid flavoured keyboards. In the pro world it doesn't matter because you can change the shortcuts to what you're used to use.

In my case the flowblade 'Y' should be 'V' and 'T' or 'R' should be 'B'. 

The tree point editing of flowblade is weird for me because it doesn't behave as other programs but that's the case for almost all edit programs on linux. They all miss the point of using 'in' and 'out' points as the basics of editing.

**Comment by jliljebl** [comment]
@lenzwerf I'll look to get the configurable shortcuts for 2.8, this has been on postponed quite some time now.

> The tree point editing of flowblade is weird for me because it doesn't behave as other programs

Can you expand on this, I based this on my experiences with Avid? There are two versions of this functionality. **Overwrite Clip** and **Overwrite Range**.

**Comment by lenzwerf** [comment]
> Can you expand on this, I based this on my experiences with Avid? There are two versions of this functionality. **Overwrite Clip** and **Overwrite Range**.

Let's say the "insert range" function is missing. And I don't understand why there have to be so many different commands. Two would be enough: insert and overwrite into timeline.
If I set an in point in the timeline and an in-out in the source I would like to be able to insert the source range from the in point on the timeline or overwrite. 
It should also be possible if you use an out point in the timeline. The range of the source clip should then go before the out point. Insert and overwrite should work in both circumstances, just like avid does with only 'B' and 'V'.

I hope my explanation was clear. It's difficult to put it to words but I can make a video of  what I mean. I can show it on Davinci Resolve or show how complicated it works in Flowblade. 

I'd like to use flowblade on a chromebook with a linux dual boot, to make YouTube video's while traveling. Flowblade feels smooth/light enough to do this so keep up the good work.

**Comment by jliljebl** [comment]
I read the explanations and I got:
  * you want to insert from monitor to timeline using **Mark In**, not insert into nearest cut to playhead . With Flowblade you need select insert frame with playhead, hit **X** to cut and then **Y** to insert. You would like to hit **I** to create **Mark In** and **V** to cut and insert in one go, right?
* 3-point overwrite does not work with only **Mark Out** set and instead of **T** or **R** you would want shortcut key **B** ?

Is this correct? If not, maybe you could do that video, that might help me to understand.

**Comment by jliljebl** [comment]
Or do you want to insert at playhead position without **Mark In** set, just single press of **V** key?

**Comment by dvdlvr** [comment]
@janne, I'm pretty sure I submitted a pull request quite some time ago for the configurable shortcuts, but you didn't want to fully implement it at the time. You just used the switch between 2 options. I can't remember what I did exactly but I'll see if it's still on my harddrive somewhere and if it can be easily integrated in the current code. I'll let you know soon, as we're now all confined to our home overhere. Sent from my Huawei tablet

**Comment by lenzwerf** [comment]
> I read the explanations and I got:
> 
> * You want to insert from monitor to timeline using **Mark In**, not insert into nearest cut to playhead. With Flowblade you need select insert frame with playhead, hit **X** to cut and then **Y** to insert. You would like to hit **I** to create **Mark In** and **V** to cut and insert in one go, right?
Yes exactly. But my 'V' key is your 'Y' so just use Y for that and if keyboard shortcuts can be changed that would solve that issue. 
> * 3-point overwrite does not work with only **Mark Out** set and instead of **T** or **R** you would want shortcut key **B** ? 
Yes, if say the R key overwrites using a single 'in' or 'out' point as well as in/out it would be great. 

The program doesn't really need extra keys for specific functions just a smart way of combining them. I found the keys to jump to 'in'or 'out' are different for the monitor and the timeline. They could be the same. And there's no shortcut for clearing in and out points but at least there's a button for that. 
> 
> Is this correct? If not, maybe you could do that video, that might help me to understand.
I'll make the video so you can see more than the theory

**Comment by jliljebl** [comment]
@dvdlvr Yes, we did merge your pull request that allows for creating configurable keyboard shortcuts  by creating and editing a text file. I mean the GUI interface to create/edit the file, Joe Q. Public will not want to edit text files to get their keyboard shortcuts.

**Comment by jliljebl** [comment]
> I found the keys to jump to 'in'or 'out' are different for the monitor and the timeline. They could be the same. 

I agree.
> And there's no shortcut for clearing in and out points but at least there's a button for that.

We can add that.  I think we captured a set of useful changes.

For 2.6 we can do:
  * Make 3-point overwrite work when only **Mark Out** has been set.
  * Make shortcuts to jump to 'in' and 'out' be same for both monitor and timeline.
  * Add shortcut for clearing 'in' and 'out' 

For 2.8 we should be able to  do:
  * Add GUI to edit keyboard shortcuts.

If you have more changes you think would useful, please open new issue as this quite long in the comments now it is easy to forget stuff that doesnot have top owb issue.

**Comment by lenzwerf** [comment]
Some of the public would want to be able to edit a text file, it's better than nothing. I managed to change the 'Y' into 'V' and 'R' into 'B' so I can work with flowblade with some additional ' getting used to' but I'm happy. A simple "how to" would probably work for some people. I always loved linux for the *.conf files. I only have basic knowledge so half the time I just do an educated gues. This time it payed of.

I started using linux at the beginning of this century and you had to edit config files to get some stuff working. I abandoned linux for a while because video and audio editing wasn't very good but with the chromebook I'm partially back on linux.

**Comment by lenzwerf** [comment]
> * Make 3-point overwrite work when only **Mark Out** has been set.

Maybe it makes more sense when the 3 point edit works with a **Mark In** set. I use them both but I think I use overwrite after a **Mark In** more

If I find other things I'll do another request or make a list in another request. Thank you for now and good luck with the Covid situation

**Comment by dvdlvr** [comment]
@lenzwerf

In the Documentation folder of the Flowblade installation you can find a 
document called Flowblade-Patch-Shortcuts.pdf.
Appendix A of this document contains a good description of how the xml 
files for shortcuts work.

**Comment by chiboreache** [comment]
oh god, it looks like INDUSTRIAL STANDARD software for windows, **where is our absolute customisation???**

**Comment by jliljebl** [comment]
In repo here is GUI for doing this now too, feature will be in 2.8. Not all shortcuts will be configurable, e.g **1-9** for edit tools and **Control+S** will not be configurable.

**Comment by Shamaoke** [comment]
> 1-9 for edit tools ... will not be configurable

Is there any reason for this?

**Comment by jliljebl** [comment]
Design decision. We have considered to maybe make it possible to add user defined additional shortcuts for edit tools, there was a request for the feature and I think I sort of agreed to doing that, but not sure if we get this for 2.8.

**Comment by Shamaoke** [comment]
@jliljebl Understood. It will be neat to have them configurable.
