### ISSUE TITLE
Minor bug: "Change project profile" problem

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#419]
It's impossible to save the new profile to a custom directory. Steps to reproduce:
1. Project > Change Project Profile
2. Select new profile
3. Open "Folder", scroll down to "Other..."
4. Select any custom folder and click "Open"
5. Click "Save With Changed Profile" - the window remains and there is no response whatsoever.

**Comment by jliljebl** [comment]
..so if you

6. Select "File -> Open..."
7. Go to folder you have selected in steps 3/4
8. Open saved project file with changed profile

..this does not work?

**Comment by Efenstor** [comment]
Just sorted it out: the problem happens only if the custom folder name contains non-Latin characters. If it's all-Latin there's no problem.

**Comment by jliljebl** [comment]
Confirmed.

**Comment by jliljebl** [comment]
Fixed in repo, will be in 1.14.

**Comment by Efenstor** [comment]
Seems that the bug is not completely fixed: the problem with non-Latin folders is fixed, but the problem with non-Latin project names persists. If I try to change the project name to a Cyrillic name then there again is no response to the "Save With Changed Profile" button. If I change the name to Latin characters it's saved successfully.

**Comment by jliljebl** [comment]
OK, will check before release.

18.2.2018 8.04 ip. "Efenstor" <notifications@github.com> kirjoitti:

**Comment by jliljebl** [comment]
No, I can't reproduce this. Can you post the terminal output, no response generally means that we have useful output from terminal.

**Comment by Efenstor** [comment]
Paradoxically, when I run the program from the terminal emulator (Gnome3), there is no problem whatsoever, but if I run it via a .desktop file or with Alt+F2, there is. So, to get the output, I ran it with Alt+F2 dumping the stdout into a file. And there's nothing special. When I click the button, nothing is dumped into the file. I have attached the full file.
[flowblade.log](https://github.com/jliljebl/flowblade/files/1751726/flowblade.log)

**Comment by jliljebl** [comment]
Ok, thanks.

Damn, these are the worst, but we might have had something similar earlier, so there could be a wway forward.

**Comment by jliljebl** [comment]
I think it is related to this #341. I removed all prints with possible non-ascii characters from save/load. Can you test if current repo head with latest patch "Remove all prints with possible non-latin characters from save/load to fix possible issues" fixes this?

**Comment by Efenstor** [comment]
Yep, it worked! Great work, Janne!

**Comment by jliljebl** [comment]
Glad it was the same, otherwise I would have had no idea on what's going on. Unfortunately we just cannot print any user strings now, I don't why this is, but that seems to be the case.
