### ISSUE TITLE
Full lenght render not range of sequence

### ISSUE THREAD

**Issue by animationista** [jliljebl/flowblade#571]
Rendering sequences with full length render range I expect the rendered file to be the length of the timeline. 
Not so.
If the original length of a clip in the timeline is longer than the final sequence length the rendered movie is this long rather than the sequence length even if the clip is trimmed down. White is added at the end of the clip to fill out the length.

Using Flowblade for ProRes rendering of clips so all sequences here is one shot long.

Using audio from mp4 reference clips added to animated png image sequences.
Video is muted, audio is used from reference clips. All refs have 100 frames head which is trimmed off in timeline. Every sequence has a new reference clip.

25 rendered sequences in total.
11 sequences does not use the reference clips at all. Only image sequences. These are rendered with proper length.

3 sequences does use reference clip audio but renders the proper length anyway. These three are working as expected.

11 clips all have the length of the reference clip rather than the length of the timeline. Sync is kept so reference clips is trimmed 4 seconds at start, but in render 4 seconds of white is added to the end.
- Of these 11, 2 renders is neither the length of the reference clips nor the sequence but instead about double the length of the sequences, further adding to the confusion. I have not found any cause for this...

Please include the following information.
1) Flowblade version (Help->About): 1.16.0
2) MLT version (Help->Runtime Environment): 6.6.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.04.1

**Comment by jliljebl** [comment]
I did 5-6 tries to reproduce the Issue, but it is not happening here.

One thing we can do to move forward is if you create a sequence that displays this issue, save it with "Save Bakcup Snapshot..." create archive of the created directory and make it available for download somewhere. Then I can hopefully reproduce the Issue and fix it.

**Comment by jliljebl** [comment]
@synk-a-dynka I pushed a fix, can you test if the repository version fixes your issue?

**Comment by animationista** [comment]
I tried rendering the same sequences again with 2.0 and I still get this issue.
I created a backup snapshot but can't share it publicly. Do you have a mail?
In this scene the image sequence is 19 seconds long, the audio is 23sec (100fr. head), but the rendered file is 40 seconds long...

**Comment by jliljebl** [comment]
Yes, its in the front page: janne.liljeblad@gmail.com

Please, do send snapshot, that could be helpful. I'll delete the data when matter is concluded.

**Comment by bidetaggle** [comment]
Same problem, 2:51 timeline but 4:12 of rendered video with white screen and noisy audio at the end
https://ufile.io/qt8d17sp

**Comment by jliljebl** [comment]
Thanks, i missed the download on first quick look, but got it now.

**Comment by jliljebl** [comment]
@animationista I fixed your bug and deleted your data, there was some quite questionable old code involved, good thing I got to look at it.
@bidetaggle you seem to have different bug, I will return to that later.

**Comment by jliljebl** [comment]
@bidetaggle Ok, got around to testing this and  the problem does not reproduce. The rendered file for last_call project is 2:51 as expected.

I'm closing this as fixed, if problem persists we can reopen or create new Issue.
